//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foody.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLike
    {
        public int PostLikeID { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.DateTime> LikeTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Post Post { get; set; }
    }
}
